# Generated by Django 4.0.4 on 2022-05-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personaje',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('imagen', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=4)),
            ],
        ),
    ]
